language: haskell

install:
    - cabal update
    - cabal install --force-reinstalls mega-sdist hspec cabal-meta cabal-src
    - cabal-meta install --force-reinstalls

script:
    - echo Done
    - mega-sdist --test
