resolver: lts-3.7
packages:
  - ./yesod-core
  - ./yesod-static
  - ./yesod-persistent
  - ./yesod-newsfeed
  - ./yesod-form
  - ./yesod-auth
  - ./yesod-auth-oauth
  - ./yesod-sitemap
  - ./yesod-test
  - ./yesod-bin
  - ./yesod
  - ./yesod-eventsource
  - ./yesod-websockets
  - location:
      git: git@github.com:pseudonom/persistent.git
      commit: 0edba747e49c816e94c235bced16978cb729b175
    subdirs:
    - persistent

# Needed for LTS 2
extra-deps:
- wai-app-static-3.1.4.1
- http-api-data-0.2.2
